export const ROUTES = {
  HOME: "/",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  FORGET_PASSWORD: "/auth/forgetPassword",
  RESET_PASSWORD: "/auth/reset-password",
  NOVELS: "/novels",
  SEARCH: "/search",
  GENRES: "/genres",
  NOVEL_DETAIL: (id: string) => `/novels/${id}`,
  CHAPTER_READER: (novelId: string, chapterId: string) =>
    `/novels/${novelId}/chapter/${chapterId}`,
  PLACEHOLDER_COVER:
    "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='300' height='400'%3E%3Crect width='100%25' height='100%25' fill='%231e293b'/%3E%3Ctext x='50%25' y='50%25' fill='%2364748b' font-family='sans-serif' font-size='18' text-anchor='middle' dominant-baseline='middle'%3ENo Cover%3C/text%3E%3C/svg%3E",
  GROUP: "/group",
  FANPAGE: "/fanpage",
  USER: {
    ROOT: "/user",
    PROFILE: "/user/profile",
    DASHBOARD: "/user/dashboard",
    FAVORITES: "/user/bookmarks",
    HISTORY: "/user/history",
  },
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    NOVELS: "/admin/novels",
    CHAPTERS: "/admin/chapters",
    USERS: "/admin/users",
    CATEGORIES: "/admin/categories",
    AUTHORS: "/admin/authors",
    GENRES: "/admin/genres",
    TAGS: "/admin/tags",
    DESCRIPTIONS: "/admin/descriptions",
    SETTINGS: "/admin/settings",
    ADS: "/admin/ads",
    AUDIT: "/admin/audit",
    OPERATIONS: "/admin/operations",
    ANALYTICS: "/admin/analytics",
    PROFILE: "/admin/profile",
  },
  ERROR: {
    UNAUTHORIZED: "/handle-exception/401",
    FORBIDDEN: "/handle-exception/403",
  },
  API: {
    HEALTH: "/api/health",
    ANALYTICS: "/api/analytics",
    ANALYTICS_INFRASTRUCTURE: "/api/analytics/infrastructure",
    AVATAR: "/api/avatar",
    CATEGORIES: "/api/categories",
    R2_PROXY: "/api/r2/proxy",
    R2_UPLOAD: "/api/r2/upload",
    WEBHOOKS_SUPABASE: "/api/webhooks/supabase",
    NOVELS: "/api/novels",
    NOVEL: (id: string) => `/api/novels/${id}`,
    NOVEL_CHAPTERS: (novelId: string) => `/api/novels/${novelId}/chapters`,
    NOVELS_RECOMMENDATIONS: (novelId: string, limit: number) =>
      `/api/novels/recommendations?novelId=${encodeURIComponent(novelId)}&limit=${limit}`,
    NOVELS_MOST_VIEWED: (limit: number) =>
      `/api/novels?sort=most_viewed&limit=${limit}`,
    STORIES: "/api/stories",
    STORY: (id: string) => `/api/stories/${id}`,
    STORIES_VIEWS: "/api/stories/views",
    STORIES_PAGE: (queryString: string) => `/api/stories?${queryString}`,
    CHAPTERS: "/api/chapters",
    CHAPTER_BY_ID: (id: string) => `/api/chapters?id=${encodeURIComponent(id)}`,
    CHAPTERS_BY_STORY: (storyId: string) =>
      `/api/chapters?storyId=${encodeURIComponent(storyId)}`,
    SUPABASE_RPC: (name: string) => `/api/supabase/rest/v1/rpc/${name}`,
    MEDIA_PREFIX: "/api/media/",
    USER: {
      BOOKMARKS: "/api/user/bookmarks",
      BOOKMARK: (comicId: string) => `/api/user/bookmarks/${encodeURIComponent(comicId)}`,
      BOOKMARKS_TOGGLE: "/api/user/bookmarks/toggle",
      HISTORY: "/api/user/history",
    },
    ADMIN: {
      NOVELS: "/api/admin/novels",
      NOVELS_PAGE: (pageSize: number) => `/api/admin/novels?pageSize=${pageSize}`,
      NOVEL: (id: string) => `/api/admin/novels/${id}`,
      NOVEL_CHAPTER: (novelId: string, chapterId: string) =>
        `/api/admin/novels/${novelId}/chapters/${chapterId}`,
      CHAPTERS: "/api/admin/chapters",
      CHAPTER_IMAGES: (chapterId: string) =>
        `/api/admin/chapters/${chapterId}/images`,
      AUDIT: "/api/admin/audit",
      AUDIT_LOGS: (page: number, pageSize: number) => `/api/admin/audit?page=${page}&pageSize=${pageSize}`,
      ANALYTICS_DASHBOARD: "/api/admin/analytics/dashboard",
      TAXONOMY: (entity: string) => `/api/admin/taxonomy?entity=${entity}`,
      TRANSLATORS: "/api/admin/translators",
      SITE_SETTINGS: "/api/admin/site-settings",
      SITE_SETTINGS_KEYS: (keys: string) =>
        `/api/admin/site-settings?keys=${encodeURIComponent(keys)}`,
      R2_PRESIGNED_URLS: "/api/admin/r2/presigned-urls",
      R2_UPLOAD_GATEWAY: "/api/admin/r2/upload",
      R2_FILE_PREFIX: "/api/admin/r2/file/",
      STORIES_FIELD_VALUES: (field: string) =>
        `/api/admin/stories/field-values?field=${encodeURIComponent(field)}`,
      SITE_METRICS: (type: string) => `/api/admin/site-metrics?type=${type}`,
      ROLE_DISTRIBUTION: "/api/admin/role-distribution",
      PROFILES: "/api/admin/profiles?page=1&pageSize=500",
      PROFILES_BY_IDS: (ids: string) =>
        `/api/admin/profiles/by-ids?ids=${encodeURIComponent(ids)}`,
      NOTIFICATIONS: "/api/admin/notifications?pageSize=20",
      MANAGE_STORY: "/api/admin/stories",
      MANAGE_CHAPTER: "/api/admin/chapters",
      MANAGE_USER: "/api/admin/users",
    },
  },
} as const;
